service: reader-app-api
# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack
# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true
provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-2
  # 'iamRoleStatement' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-2:*:*"
functions:
  # Defines an HTTP API endpoint that calls the main function in feeds/create.js
  # - path: url path is /notes
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross domain api call
  # - authorizer: authenticate using the AWS IAM role
  # User feeds
  create-feed:
    handler: functions/user-feeds/create.main
    events:
      - http:
          path: feeds
          method: post
          cors: true
          authorizer: aws_iam
  get-feed:
    handler: functions/user-feeds/get.main
    events:
      - http:
          path: feeds/{id}
          method: get
          cors: true
          authorizer: aws_iam
  list-feeds:
    handler: functions/user-feeds/list.main
    events:
      - http:
          path: feeds
          method: get
          cors: true
          authorizer: aws_iam
  update-feed:
    handler: functions/user-feeds/update.main
    events:
      - http:
          path: feeds/{id}
          method: put
          cors: true
          authorizer: aws_iam
  delete-feed:
    handler: functions/user-feeds/delete.main
    events:
      - http:
          path: feeds/{id}
          method: delete
          cors: true
          authorizer: aws_iam
  # Feeds